### ISSUE TITLE
怎么刷新群友头像

### ISSUE THREAD

**Issue by DaBinQwQ** [koishijs/koishi-plugin-marry#4]
群友换头像了怎么刷新让机器人发新头像

**Comment by Seidko** [comment]
marry 插件每次发送头像图片的时候都是发送获取到的最新头像的，如果没有刷新的话要么是腾讯服务器没有刷新，要么是 go-cq 有缓存，插件层面不一定能解决

**Comment by Seidko** [comment]
现在测试一下是否有该问题？
