### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by AGuuGuu** [koishijs/koishi-plugin-marry#8]
### Describe the problem related to the feature request in as much detail as possible

希望可以添加一个根据头衔等级（1~100）排除部分群友，以避免娶到不活跃的群友！

### Describe the solution you'd like

希望可以根据头衔等级，进行筛选或排除

### Describe alternatives you've considered

我还考虑过根据时间段来确定能够被娶的活跃群友，比如7天内发言比较多的几位（人数可以是10人或者更多，自定义），或者15天内发言数量比较靠前的群友

**Comment by Seidko** [comment]
已在 f90901e096f21c18db49e9bb82ae25f7c2528971 做了支持。
