### ISSUE TITLE
Feature: onebot适配器升级至5.7.5~5.8.0版本后，marry插件报错

### ISSUE THREAD

**Issue by Neptune1990** [koishijs/koishi-plugin-marry#9]
### Describe the problem related to the feature request in as much detail as possible

问题描述：onebot适配器升级至5.7.5~5.8.0版本后，marry插件报错，TypeError: guildMemberList.findIndex is not a function，适配器降级也无法恢复（还原备份文件后恢复），报错信息如下图。
![image](https://github.com/koishijs/koishi-plugin-marry/assets/107494041/90721594-4bc6-4274-b6db-6b34357c163c)

环境：
System:
OS: Windows 10 10.0.19045
Binaries:
Node: 16.19.1
Yarn: 3.5.0
Koishi:
Core: 4.14.4
Console: 5.13.3
Koishi Desktop: 0.10.6

### Describe the solution you'd like

据了解是新版 onebot 引入了不兼容的更新导致。

**Comment by Seidko** [comment]
有更新计划，但是目前Q号被封，测试进度缓慢，敬请耐心等待！

**Comment by Seidko** [comment]
应该是修好了，可以测试一下
